[package]
name = "liana-gui"
version = "12.0.0"
readme = "README.md"
description = "Liana GUI"
repository = "https://github.com/wizardsardine/liana"
license = "BSD-3-Clause"
authors = ["Edouard Paris <m@edouard.paris>"]
edition = "2018"
resolver = "2"

[[bin]]
name = "liana-gui"
path = "src/main.rs"

[features]
dev-meld = ["webview", "dev-coincube"]
dev-onramper = ["webview", "dev-coincube"]

dev-coincube = []
webview = ["iced_webview"]

[dependencies]
async-trait = "0.1"
async-hwi = "0.0.29"
liana = { path = "../liana" }
lianad = { path = "../lianad", default-features = false, features = [
	"nonblocking_shutdown",
] }
liana-ui = { path = "../liana-ui" }
backtrace = "0.3"
hex = "0.4.3"

iced = { version = "0.13.1", default-features = false, features = [
	"tokio",
	"svg",
	"canvas",
	"qr_code",
	"image",
	"lazy",
	"advanced",
	"wgpu",
	"tiny-skia",
] }
iced_aw = { version = "0.12.2", features = ["context_menu"] }
iced_runtime = "0.13.1"

# Webview for embedded browser functionality
iced_webview = { git = "https://github.com/coincubetech/iced_webview.git", optional = true }

# Used to verify RFC-compliance of an email
email_address = "0.2.7"

tokio = { version = "1", features = ["signal"] }
async-fd-lock = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Used to ping bitcoind node
jsonrpc = "0.12"

# Logging stuff
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
log = "0.4"

dirs = "3.0.1"
toml = "0.5"

chrono = "0.4.38"

# Used for managing internal bitcoind
libc = "0.2"
base64 = "0.21"
bitcoin_hashes = "0.12"
reqwest = { version = "0.11", default-features = false, features = [
	"json",
	"rustls-tls",
	"stream",
] }
rust-ini = "0.19.0"
rfd = "0.15.1"
fs2 = "0.4.3"

# Used for opening URLs in browser
open = "5.3"
# Used for URL parsing in webview
url = "2.5"
# Used for JavaScript redirect detection in webview
regex = "1.10"

[target.'cfg(windows)'.dependencies]
zip = { version = "0.6", default-features = false, features = [
	"bzip2",
	"deflate",
] }

[target.'cfg(unix)'.dependencies]
tar = { version = "0.4", default-features = false }
flate2 = { version = "1.0", default-features = false }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "coincube-vault.exe"
FileDescription = "The missing safety net for your coins, Coincube's Fork"
CompanyName = "Coincube"
InternalName = "Liana"
