[workspace]
resolver = "2"
members = [
    "fuzz",
    "liana",
    "lianad",
    "liana-gui",
    "liana-ui",
]
default-members = ["liana", "lianad", "liana-gui", "liana-ui"]

[patch.crates-io]
iced_style = { git = "https://github.com/edouardparis/iced", branch = "patch-0.12.3"}
iced_winit = { git = "https://github.com/edouardparis/iced", branch = "patch-0.12.3"}
iced_futures = { git = "https://github.com/edouardparis/iced", branch = "patch-0.12.3"}
